AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS SecurityHub Findings Analyzer with Bedrock Integration'

Parameters:
  SenderEmail:
    Type: String
    Description: Email address to send findings from (must be verified in SES)
  
  RecipientEmail:
    Type: String
    Description: Email address to send findings to (must be verified in SES in sandbox)
  
  FindingsHours:
    Type: Number
    Default: 24
    Description: Number of hours of findings to analyze
    MinValue: 1
    MaxValue: 168

  LambdaCodeBucket:
    Type: String
    Description: S3 bucket containing the Lambda function code

  LambdaCodeKey:
    Type: String
    Description: S3 key (path) to the Lambda function code ZIP file

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: SecurityHubAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - securityhub:GetFindings
                Resource: '*'
        - PolicyName: SESAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ses:SendEmail
                  - ses:SendRawEmail
                Resource: '*'
        - PolicyName: BedrockAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - bedrock:InvokeModel
                Resource: '*'
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: !Sub 'arn:aws:s3:::${LambdaCodeBucket}/${LambdaCodeKey}'

  FindingsAnalyzerFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code: 
        S3Bucket: !Ref LambdaCodeBucket
        S3Key: !Ref LambdaCodeKey
      Runtime: python3.12
      Timeout: 300
      MemorySize: 256
      Environment:
        Variables:
          SENDER_EMAIL: !Ref SenderEmail
          RECIPIENT_EMAIL: !Ref RecipientEmail
          BEDROCK_MODEL_ID: 'anthropic.claude-3-sonnet-20240229-v1:0'
          FINDINGS_HOURS: !Ref FindingsHours

  EventRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "Schedule for SecurityHub Findings Analysis"
      ScheduleExpression: "cron(0 8 * * ? *)"  # Runs daily at 8 AM UTC
      State: ENABLED
      Targets:
        - Arn: !GetAtt FindingsAnalyzerFunction.Arn
          Id: "SecurityHubFindingsAnalyzer"

  EventRulePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref FindingsAnalyzerFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt EventRule.Arn

Outputs:
  LambdaFunctionArn:
    Description: ARN of the Lambda function
    Value: !GetAtt FindingsAnalyzerFunction.Arn

  LambdaRoleArn:
    Description: ARN of the Lambda execution role
    Value: !GetAtt LambdaExecutionRole.Arn